apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  p1-meter-url: {{ .Values.p1MeterUrl | quote }}
